#ifndef INVERTEDINDEX_H
#define INVERTEDINDEX_H

/* Program Name: InvertedIndex.h 
*  Author: Generated by ChatGPT using prompts by Kyle Ingersoll
*  Date last updated: 12/3/2024
*  Purpose: To create a class prototype for the inverted index data structure
*/

#include "FuzzyMatcher.h"
#include <unordered_map>
#include <set>
#include <string>
#include <vector>

class InvertedIndex {
private:
    // Map each word to a set of index numbers for uniqueness and fast lookups
    std::unordered_map<std::string, std::set<int>> index;
    std::vector<std::string> documents;

public:
    // Add file and populate the index
    void addFile(const std::string& filePath);

    // Perform exact search
    std::set<int> search(const std::string& word) const;

    // Perform fuzzy search and return matching indices
    std::set<int> fuzzySearch(const std::string& query, int maxDistance) const;

    const std::unordered_map<std::string, std::set<int>>& getIndex() const;
};

#endif // INVERTEDINDEX_H

