#ifndef SCREEN2_H
#define SCREEN2_H

/* Program Name: Screen2.h
*  Author: Generated by ChatGPT using prompts by Kyle Ingersoll
*  Date last updated: 12/2/2024
*  Purpose: To create a class prototype for Screen 2.
*/

#include <windows.h>
#include <string>
#include "InvertedIndex.h"

class Screen2 {
private:
    HWND hwndExactResults;
    HWND hwndFuzzyResults;
    std::string filePath;

public:
    void createScreen(HINSTANCE hInstance, const std::string& filePath);
    static LRESULT CALLBACK WndProc(HWND, UINT, WPARAM, LPARAM);
};

#endif // SCREEN2_H


