#ifndef SCREEN2_H
#define SCREEN2_H

/* Program Name: Screen2.h
*  Author: Generated by ChatGPT using prompts by Kyle Ingersoll
*  Date last updated: 12/8/2024
*  Purpose: To create a class prototype for Screen 2.
*/

#include <string>
#include "InvertedIndex.h"
#include "FuzzyMatcher.h"
#include <windows.h>
#include <memory>

class Screen2 {
public:
    // Default constructor
    Screen2();

    void createScreen(HINSTANCE hInstance, const std::string& filePath);
    void performSearch(HWND hwnd, const std::string& searchText, int maxDistance);
    void highlightResults(HWND hwndResultsBox, const std::set<int>& matches, const InvertedIndex& index);
    HWND gethwndSearchBox() const;
private:
    HWND hwndExactResults;
    HWND hwndFuzzyResults;
    HWND hwndSearchBox;

    InvertedIndex invertedIndex; // Instance of the InvertedIndex class
    std::unique_ptr<FuzzyMatcher> fuzzyMatcher;          // Pointer for deferred initialization
};

#endif // SCREEN2_H


