#ifndef SCREEN2_H
#define SCREEN2_H

/* Program Name: Screen2.h
*  Author: Generated by ChatGPT using prompts by Kyle Ingersoll
*  Date last updated: 12/3/2024
*  Purpose: To create a class prototype for Screen 2.
*/

#include <string>
#include "InvertedIndex.h"
#include "FuzzyMatcher.h"

class Screen2 {
public:
    void createScreen(HINSTANCE hInstance, const std::string& filePath);
private:
    HWND hwndExactResults;
    HWND hwndFuzzyResults;
    HWND hwndSearchBox;
    InvertedIndex invertedIndex; // Instance of the InvertedIndex class
    FuzzyMatcher fuzzyMatcher;   // Instance of the FuzzyMatcher class

    void performSearch(HWND hwnd, const std::string& searchText);
    void highlightResults(HWND hwnd, const std::wstring& text, const std::vector<size_t>& positions);
};

#endif // SCREEN2_H


